---
## from https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml
sudo: required

env:
## no opensuse bro repository for precise or centos6
#  - distribution: centos
#    version: 6
#    init: /sbin/init
#    run_opts: ""
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
  - distribution: ubuntu
    version: 16.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
## FIXME! travis stalling after 10min for trusty...
#  - distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""
#  - distribution: ubuntu
#    version: 12.04
#    init: /sbin/init
#    run_opts: ""
#  - distribution: alpine
#    version: 3.4
#    init: /sbin/init
#    run_opts: ""
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default-ja3
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default-pdns
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default-HEAD

services:
  - docker

before_install:
  # - sudo apt-get update
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  - env
  - pwd
  - find -ls
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
  - cp test/travis/initctl_faker test/
  # Customize container
  - 'sudo docker build --rm=true --file=test/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible test'

script:
  - container_id=$(mktemp)
    # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD%/*}":/etc/ansible/roles:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible --version'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.broids/test/integration/${suite}/default.yml --syntax-check'

  # Test role.
  - 'travis_wait 30 sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.broids/test/integration/${suite}/default.yml -vvvv'

  # Test role idempotence.
## known fail
  - >
    sudo docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.broids/test/integration/${suite}/default.yml
    | tee /tmp/idempotency.log
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)

after_failure:
  # Check what happened on system.
  - 'sudo docker exec --tty "$(cat ${container_id})" awk "/temporary password/ { print \$NF }" /var/log/mysqld.log'

after_script:
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status mysql.service'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status bro.service'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -la /var/log/'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -la /var/log/mysql /var/log/mariadb'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/mysql/mysql.log /var/log/mariadb/mariadb.log'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/mysql/error.log'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -la /var/lib/mysql'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /root/.my.cnf'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm find /etc/mysql/ -iname "*.cnf" -exec cat {} \;'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm mysqladmin -u root -p status'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -la /var/log/bro/current /var/spool/bro/bro /opt/bro/logs/current/'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/bro/current/stdout.log'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/bro/current/stderr.log'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm netstat -anp'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ss -nlp'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ps auxw'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm journalctl -xe --no-pager'

  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
