---
## Note: if you edit anything here, adapt templates/local.bro as needed

- name: git clone seth hall APT1
  git:
    repo=https://github.com/sethhall/bro-apt1
    dest={{ broids_site }}/apt1
- name: git clone Crowdstrike bro scripts
  git:
    repo=https://github.com/CrowdStrike/cs-bro.git
    dest={{ broids_site }}/cs-bro
- name: git clone jonschipp bro scripts
  git:
    repo=https://github.com/jonschipp/bro-scripts.git
    dest={{ broids_site }}/jonschipp-bro
- name: git clone securitykitten bro scripts
  git:
    repo=https://github.com/securitykitten/bro_scripts.git
    dest={{ broids_site }}/securitykitten-bro
- name: git clone fox-it bro scripts
  git:
    repo=https://github.com/fox-it/bro-scripts.git
    dest={{ broids_site }}/foxit-bro
- name: git clone criticalstack bro scripts
  git:
    repo=https://github.com/criticalstack/bro-scripts.git
    dest={{ broids_site }}/foxit-bro

## Anything to recover?
##  https://github.com/Security-Onion-Solutions/securityonion-bro-scripts
## https://github.com/LiamRandall/bro-scripts
## https://github.com/sethhall/bro-scripts
## https://github.com/TravisFSmith/MyBroElk
## https://gist.github.com/mavam/5028034

## https://github.com/thnyheim/misp2bro; https://github.com/MISP/MISP/issues/424

