---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Debian | Install Bro dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - gdb
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: Debian-based | install bro
  include: debian.yml
  when: not force_source_build and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Redhat-based | install bro
  include: redhat.yml
  when: not force_source_build and (ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: install bro from source
  include: source.yml
  when: force_source_build


## Extra configuration
- name: Add BROPATH to /etc/profile
  lineinfile: 'dest=/etc/profile regexp="{{ item.regexp }}" line="{{ item.line }}" state=present create=yes'
  with_items:
    - { regexp: '^export BROPATH=', line: 'export BROPATH={{ bro_prefix }}' }
    - { regexp: '^export PATH=', line: 'export PATH=$PATH:$BROPATH/bin' }
#- name: young-ssl bro script
#  copy:
#    src=young-ssl.bro dest={{ broids_site }}/young-ssl.bro mode=644
## https://github.com/JustinAzoff/bro_scripts
- name: Extra bro script
  copy:
    src={{ item }} dest={{ broids_site }}/{{ item }} mode=644
  with_items:
    - file_analysis_02.bro
- name: add bro local configuration
  template: src=local.bro dest="{{ broids_site }}/local.bro" mode=0644 backup=yes
  notify:
    - restart bro

## Note: file is created by broctl: install and {{ broids_spool }}/broctl-config.sh -> {{ bro_prefix }}/share/broctl/scripts/broctl-config.sh
- stat: path={{ broids_spool }}/broctl-config.sh
  register: st
- name: Reset send-mail config (not used by default)
  lineinfile: 'dest={{ broids_spool }}/broctl-config.sh regexp="{{ item.regexp }}" line="{{ item.line }}" state=present'
  with_items:
## FIXME! not working/not idempotent ??? changed all time.
    - { regexp: '^sendmail=', line: 'sendmail=\"\"' }
  when: st.stat.exists
#  notify:
#    - restart bro

- cron: name="bro maintainance" minute="0-59/5"
        user="root" job="{{ bro_prefix }}/bin/broctl cron"
        cron_file=ansible_bro

- name: Configure node.cfg
  template: src=node.cfg dest={{ broids_etc }}/node.cfg mode=0664 owner=root group={{ broids_group }}
  notify:
    - restart bro

## http://nullsecure.org/building-your-own-passivedns-feed/
## OR ? http://stackoverflow.com/questions/16444306/ansible-idempotent-mysql-installation-playbook
## is mysql_install_db necessary? probably not
#- name: setup database
#  command: "{{ item }}"
#  with_items:
#    - mysql_install_db
#    - mysql_secure_installation    ## interactive

- name: check that mysql is running
  service: "name={{ mysql_svc }} state=started"
#- stat: path=/root/.my.cnf
#  register: mycnf
#- debug: var=mycnf
#- stat: path=/var/run/mysqld/mysqld.sock
#  register: mysock
#- debug: var=mysock
#- name: check mysql socket configuration
#  shell: "grep -rin sock {{ mysql_confdir }}/* /etc/my.cnf"
#  register: myconf
#  changed_when: false
#  ignore_errors: true
#- debug: var=myconf.stdout_lines

- name: Set mysql root user password
  mysql_user: name=root
              host="{{ item }}"
              password="{{ mysql_root_password }}"
              check_implicit_admin=yes
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_old_root_password }}"
              state=present
  with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
  ignore_errors: true
- mysql_db: name=pdns state=present login_user="{{ mysql_user }}" login_password="{{ mysql_root_password }}"
- mysql_user: name={{ mysql_pdns_user }} password={{ mysql_pdns_pass }} priv=pdns.*:ALL state=present login_user="{{ mysql_user }}" login_password="{{ mysql_root_password }}"
- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent" login_user="{{ mysql_user }}" login_password="{{ mysql_root_password }}"
- name: remove the MySQL test database
  action: mysql_db db=test state=absent login_user="{{ mysql_user }}" login_password="{{ mysql_root_password }}"
- name: Install Pdns requirements
  pip: name=bottle state=present

- name: git clone bro-pdns
  git:
    repo=https://github.com/JustinAzoff/bro-pdns.git
    dest={{ broids_site }}/bro-pdns

- name: create directory for extracted files
  file: dest="{{ item }}" state=directory mode=0755
  with_items:
    - "{{ bro_extractedfiles }}/http"
    - "{{ bro_extractedfiles }}/ftp"

- include: bro-scripts.yml

- include: critical-stack.yml
  when: bro_cs_enable is defined and bro_cs_enable and bro_cs_apikey is defined and bro_cs_apikey != ''

- name: Ending bro configuration
  command: "{{ item }}"
  with_items:
    - "{{ broids_broctl }} install"
    - "{{ broids_broctl }} check"
  notify:
    - restart bro

#- name: start BRO_PDNS API service
#  command: "BRO_PDNS_DB=mysql://{{ mysql_pdns_user }}::{{ mysql_pdns_pass }}@localhost/pdns {{ broids_site }}/bro-pdns/bro_pdns.py serve"

# Test
# curl http://localhost:8081/dns/www.youtube.com

- include: monit.yml

