---

- name: check bro
  command: "{{ broids_broctl }} check"

- name: deploy zeek
  command: "{{ broids_broctl }} zeek"
  when: use_zeek_opensuse_repo

- name: restart bro
  command: "{{ broids_broctl }} restart"

- name: restart monit
  service: name=monit state=restarted

- name: fetch critical-stack-intel feeds
  command: critical-stack-intel pull

- name: Restart apparmor
  service: name=apparmor state=restarted
  when: travisci is defined and travisci
